#!/bin/bash

if [ $# -ne 1 ]; then
	exit 1
fi

cat $1 | cut -d' ' -f 2 | sort | uniq -c | sort -n | tail -3 | tr -s ' ' | cut -d' ' -f3 | 
while read line;
do
	http2=$(awk -v l=$line 'BEGIN{sum = 0} $2 == l && $8 == "HTTP/2.0" {sum+=1} END{print sum}' $1)
	nonHttp2=$(awk -v l=$line 'BEGIN{sum = 0} $2 == l && $8 != "HTTP/2.0" {sum+=1} END{print sum}' $1)
		
	echo "$line HTTP/2.0: $http2 non-HTTP/2.0: $nonHttp2" 

	awk -v l=$line '$2 == l && $9 > 302 {print $1}' $1 | sort | uniq -c | sort -nr | head -5
	
done
exit 0
