#!/bin/bash

[ $# -ne 2 ] && { echo "Enter 2 args!"; exit 1; }
[ -d $2 ] || { echo "Not a directory!"; exit 2; }
[ -f $1 ] && { echo "File already exists :O"; exit 3; }

touch $1

cat $(find $2 -type f | head -1) | awk 'NR != 9 && NR != 1 {print $0}' | tr -s ' ' | cut -d":" -f1 | sed -E 's/(.*) /\1/g' | tr '\n' ',' > $1

echo -e "\n" >> $1

while read line
do
	awk 'NR != 1 && NR != 9 {print $0}' $line | tr -d ' ' | cut -d':' -f2 | tr '\n' ',' >> $1
	echo -e "\n" >> $1
	
done < <(find $2 -type f) 

exit 0
